version: "3"

services:
  backend:
    build: backend/
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app:cached
      - /app/.venv
  frontend:
    build: frontend/
    command: npm start
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
  nginx:
    build: nginx/
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    volumes:
      - ./nginx/config:/etc/nginx:cached
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
